% Serie de Fibonacci
% Each new term in the Fibonacci sequence is generated by adding the previous two terms.
% By starting with 1 and 2, the first 10 terms will be:
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
% find the sum of the even-valued terms.
% https://projecteuler.net/problem=2
%
% Autor: Oscar Calvo
% Fecha: Agosto 28/2013
% % Licencia: Este archivo está bajo la licencia GPL-3.0. Ver LICENSE en el repositorio.
%
close all, clear all, clc;
f = zeros(32,1);
f(1) = 1;
f(2) = 2;
tic
for k = 3:32
   f(k) = f(k-1) + f(k-2);
end
l=1;
for i=1:32
    if mod(f(i),2)==0;
        v(l)=f(i);
        l=l+1;
    end
end
s=sum(v);
toc
fprintf('La respuesta es %.0d\n',s)
